### ISSUE TITLE
Pressing the `enter` key when no TODOs exist should not show blank terminal

### ISSUE THREAD

**Issue by jakeisnt** [sdrshnv/tjern#2]
I was confused by this when trying the app. When initially logging in - before adding any TODOs - the first instruction I see is to press the enter key, so I try it -- but the enter key shows a black screen!

Pressing the enter key when no TODOs exist should prompt to create a new TODO, show a message about having to create a TODO before using -- it should be anything other than a black screen

**Comment by sdrshnv** [comment]
Added error message
