### ISSUE TITLE
don't show login page if i will be automatically logged in

### ISSUE THREAD

**Issue by jakeisnt** [sdrshnv/tjern#3]
continuation of https://github.com/sudarshanvankudre/tjern/issues/1

it's confusing to run `tjern` and see the login page even though i thought i was already logged in!

maybe a 'splash page' could be shown or a loading page instead, but when i see the login page, i try to interact with it, then am quickly redirected to the logged in view

**Comment by sdrshnv** [comment]
Resolved in upcoming release
