### ISSUE TITLE
Shortcut: CMD-n for new?

### ISSUE THREAD

**Issue by jakeisnt** [sdrshnv/tjern#4]
CMD key is closer to my left thumb than CTRL on macs -> much easier to press

**Comment by sdrshnv** [comment]
What do you think about just having `n` as the shortcut?

**Comment by jakeisnt** [comment]
Maybe!

Pro: much easier to trigger. feels faster to interact with
Cons:
- prevents you from adding input boxes to main page (shortcut would conflict)
- future need for more modal operations - could be too complex for users

**Comment by sdrshnv** [comment]
Using `n` for now, will look into cmd-n later
