### ISSUE TITLE
Quick entry special chars

### ISSUE THREAD

**Issue by sdrshnv** [sdrshnv/tjern#6]
```
tjern -n I'm foo
```
doesn't work as expected, the entry doesn't have the `'` in it

**Comment by jakeisnt** [comment]
: ' (

**Comment by sdrshnv** [comment]
Putting special character entries between double quotes fixes this. Handling single quotes is tricky since they're expected to be closed in the terminal. 
```
tjern -n "I'm foo"
``` 
should suffice for now
