### ISSUE TITLE
Idea: press 'q' to exit viewing a single note

### ISSUE THREAD

**Issue by jakeisnt** [sdrshnv/tjern#7]
motivation:
- 'q' is closer than 'esc' to fingers on standard keyboards
- other cli tools - like postgres' `pctl`, `bat`, etc - use this shortcut also

**Comment by jakeisnt** [comment]
I use a lot of other CLI programs with this shortcut, so - not thinking - tried to use it with tjern and it didn't do the same thing!

**Comment by sdrshnv** [comment]
Included in upcoming release
